# -*- coding: utf-8 -*-
"""stock_analysis_streamlit.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVrsDRbw-djTzpdb7eeU9MUPNL6-v1gZ
"""

!pip install streamlit yfinance pandas numpy plotly pyngrok

"""
Streamlit Stock Analysis & Live Signal App
Filename: stock_analysis_streamlit.py

What it does:
- Lets user input a ticker (NSE/NYSE/etc.) and fetches live/historical price data using yfinance or Alpha Vantage (optional API key).
- Computes standard technical indicators (SMA, EMA, MACD, RSI, Bollinger Bands).
- Builds a simple rule-based scoring system that aggregates indicator signals into a final recommendation: BUY / HOLD / SELL with confidence.
- Displays interactive charts, data table, and a basic backtest summary for the chosen strategy.

Dependencies:
- streamlit
- yfinance
- pandas
- numpy
- plotly

Optional (only if you want Alpha Vantage fallback):
- alpha_vantage

Install with:
pip install streamlit yfinance pandas numpy plotly
# optional: pip install alpha_vantage

Run:
streamlit run stock_analysis_streamlit.py

Notes:
- Streaming / live means we fetch the most recent market data each time the page runs or the user clicks "Refresh".
- For US tickers use e.g. AAPL, MSFT. For Indian tickers you can try NSE:INFY.NS etc. (yfinance format).
- This app is a demo and educational. Not financial advice.

"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objs as go
from datetime import datetime, timedelta

# ------------------------- Indicator functions -------------------------

def compute_sma(df, period):
    return df['Close'].rolling(window=period).mean()


def compute_ema(df, period):
    return df['Close'].ewm(span=period, adjust=False).mean()


def compute_macd(df, fast=12, slow=26, signal=9):
    ema_fast = df['Close'].ewm(span=fast, adjust=False).mean()
    ema_slow = df['Close'].ewm(span=slow, adjust=False).mean()
    macd = ema_fast - ema_slow
    macd_signal = macd.ewm(span=signal, adjust=False).mean()
    macd_hist = macd - macd_signal
    return macd, macd_signal, macd_hist


def compute_rsi(df, period=14):
    delta = df['Close'].diff()
    up = delta.clip(lower=0)
    down = -1 * delta.clip(upper=0)
    ma_up = up.rolling(window=period).mean()
    ma_down = down.rolling(window=period).mean()
    rs = ma_up / ma_down
    rsi = 100 - (100 / (1 + rs))
    return rsi


def compute_bollinger(df, period=20, stds=2):
    sma = df['Close'].rolling(period).mean()
    std = df['Close'].rolling(period).std()
    upper = sma + stds * std
    lower = sma - stds * std
    return upper, lower

# ------------------------- Scoring / Signal logic -------------------------

def score_signals(df):
    """Return (score, signals dict) where score is from -100 (strong sell) to +100 (strong buy)."""
    signals = {}
    score = 0

    # SMA cross (20 vs 50)
    if df['SMA20'].iloc[-1] > df['SMA50'].iloc[-1]:
        signals['SMA'] = 'bullish'
        score += 20
    else:
        signals['SMA'] = 'bearish'
        score -= 20

    # EMA momentum (EMA12 vs EMA26)
    if df['EMA12'].iloc[-1] > df['EMA26'].iloc[-1]:
        signals['EMA'] = 'bullish'
        score += 15
    else:
        signals['EMA'] = 'bearish'
        score -= 15

    # MACD histogram positive
    if df['MACD_HIST'].iloc[-1] > 0:
        signals['MACD'] = 'bullish'
        score += 15
    else:
        signals['MACD'] = 'bearish'
        score -= 15

    # RSI thresholds
    rsi = df['RSI'].iloc[-1]
    if rsi < 30:
        signals['RSI'] = 'oversold'
        score += 20
    elif rsi > 70:
        signals['RSI'] = 'overbought'
        score -= 20
    else:
        signals['RSI'] = 'neutral'

    # Price vs Bollinger
    if df['Close'].iloc[-1] < df['BB_lower'].iloc[-1]:
        signals['Bollinger'] = 'below_lower'
        score += 10
    elif df['Close'].iloc[-1] > df['BB_upper'].iloc[-1]:
        signals['Bollinger'] = 'above_upper'
        score -= 10
    else:
        signals['Bollinger'] = 'within'

    # Volume spike check (compare last volume to 20-day avg)
    vol_avg20 = df['Volume'].rolling(20).mean().iloc[-1]
    if not np.isnan(vol_avg20) and df['Volume'].iloc[-1] > 1.8 * vol_avg20:
        signals['Volume'] = 'spike'
        score += 10
    else:
        signals['Volume'] = 'normal'

    # Clamp score to -100..100
    score = max(-100, min(100, score))
    return score, signals

# ------------------------- Simple backtest -------------------------

def simple_backtest(df):
    """A very simple backtest: buy when score>30, sell when score<-30. Calculate CAGR and total return."""
    cash = 0.0
    position = 0.0
    entry_price = 0.0
    trades = []

    for i in range(30, len(df)):
        window = df.iloc[:i+1]
        score, _ = score_signals(window)
        price = df['Close'].iloc[i]

        if score > 30 and position == 0:
            # buy 1 unit
            position = 1
            entry_price = price
            trades.append(('BUY', df.index[i], price))
        elif score < -30 and position == 1:
            # sell
            pnl = price - entry_price
            cash += pnl
            position = 0
            trades.append(('SELL', df.index[i], price, pnl))

    # close at last
    if position == 1:
        pnl = df['Close'].iloc[-1] - entry_price
        cash += pnl
        trades.append(('CLOSE', df.index[-1], df['Close'].iloc[-1], pnl))

    total_return = cash  # since we used 1 unit buys, return is cash profit
    return {'trades': trades, 'total_return': total_return}

# ------------------------- Streamlit UI -------------------------

st.set_page_config(page_title="Stock Live Analyzer", layout='wide')
st.title('Stock Market — Live Analysis & Simple Signal Engine')

col1, col2 = st.columns([2, 1])

with col1:
    ticker = st.text_input('Ticker (e.g. AAPL or INFY.NS)', value='AAPL')
    period = st.selectbox('Historical Period', options=['1mo','3mo','6mo','1y','2y','5y'], index=3)
    interval = st.selectbox('Interval', options=['1d','1h','30m'], index=0)
    use_alpha = st.checkbox('Use Alpha Vantage (fallback) if yfinance fails', value=False)
    alpha_key = None
    if use_alpha:
        alpha_key = st.text_input('Alpha Vantage API Key (optional)')

with col2:
    st.write('## Actions')
    if st.button('Refresh / Analyze'):
        st.session_state['run'] = True
    else:
        if 'run' not in st.session_state:
            st.session_state['run'] = False

    st.write('Click *Refresh / Analyze* to fetch latest data and recompute signals.')

if st.session_state['run']:
    with st.spinner('Fetching data...'):
        try:
            data = yf.download(ticker, period=period, interval=interval, progress=False, threads=False)
            if data.empty:
                raise Exception('yfinance returned empty data')
        except Exception as e:
            st.warning(f'yfinance failed: {e}')
            data = pd.DataFrame()

        if data.empty and use_alpha and alpha_key:
            st.info('Attempting Alpha Vantage fallback...')
            try:
                from alpha_vantage.timeseries import TimeSeries
                ts = TimeSeries(key=alpha_key, output_format='pandas')
                if interval == '1d':
                    av_data, _ = ts.get_daily_adjusted(symbol=ticker, outputsize='compact')
                    av_data = av_data.rename(columns={
                        '5. adjusted close':'Close','6. volume':'Volume','1. open':'Open','2. high':'High','3. low':'Low'
                    })
                    av_data.index = pd.to_datetime(av_data.index)
                    av_data = av_data.sort_index()
                    data = av_data[['Open','High','Low','Close','Volume']]
                else:
                    av_data, _ = ts.get_intraday(symbol=ticker, interval='60min' if interval=='1h' else '30min', outputsize='compact')
                    av_data.index = pd.to_datetime(av_data.index)
                    av_data = av_data.sort_index()
                    data = av_data[['1. open','2. high','3. low','4. close','5. volume']]
                    data.columns = ['Open','High','Low','Close','Volume']
            except Exception as e:
                st.error(f'Alpha Vantage fallback failed: {e}')

    if data.empty:
        st.error('No data available for this ticker/interval. Try another ticker or longer period.')
    else:
        df = data.copy()
        # ensure numeric
        df[['Open','High','Low','Close','Volume']] = df[['Open','High','Low','Close','Volume']].apply(pd.to_numeric, errors='coerce')

        # indicators
        df['SMA20'] = compute_sma(df, 20)
        df['SMA50'] = compute_sma(df, 50)
        df['EMA12'] = compute_ema(df, 12)
        df['EMA26'] = compute_ema(df, 26)
        macd, macd_signal, macd_hist = compute_macd(df)
        df['MACD'] = macd
        df['MACD_SIGNAL'] = macd_signal
        df['MACD_HIST'] = macd_hist
        df['RSI'] = compute_rsi(df, 14)
        bb_upper, bb_lower = compute_bollinger(df, 20, 2)
        df['BB_upper'] = bb_upper
        df['BB_lower'] = bb_lower

        # score
        score, signals = score_signals(df)

        # Recommendation text
        rec = 'HOLD'
        if score >= 40:
            rec = 'STRONG BUY'
        elif score >= 10:
            rec = 'BUY'
        elif score <= -40:
            rec = 'STRONG SELL'
        elif score <= -10:
            rec = 'SELL'

        # Top summary
        st.subheader(f'Recommendation: {rec}  (score {score})')
        st.write('Signal breakdown:')
        st.json(signals)

        # Layout: price chart + indicator chart
        fig_price = go.Figure()
        fig_price.add_trace(go.Candlestick(x=df.index, open=df['Open'], high=df['High'], low=df['Low'], close=df['Close'], name='Price'))
        fig_price.add_trace(go.Scatter(x=df.index, y=df['SMA20'], name='SMA20'))
        fig_price.add_trace(go.Scatter(x=df.index, y=df['SMA50'], name='SMA50'))
        fig_price.add_trace(go.Scatter(x=df.index, y=df['EMA12'], name='EMA12'))
        fig_price.update_layout(height=500, margin=dict(t=30))

        fig_macd = go.Figure()
        fig_macd.add_trace(go.Bar(x=df.index, y=df['MACD_HIST'], name='MACD Hist'))
        fig_macd.add_trace(go.Scatter(x=df.index, y=df['MACD'], name='MACD'))
        fig_macd.add_trace(go.Scatter(x=df.index, y=df['MACD_SIGNAL'], name='Signal'))
        fig_macd.update_layout(height=250, margin=dict(t=10))

        fig_rsi = go.Figure()
        fig_rsi.add_trace(go.Scatter(x=df.index, y=df['RSI'], name='RSI'))
        fig_rsi.add_hline(y=70, line_dash='dash')
        fig_rsi.add_hline(y=30, line_dash='dash')
        fig_rsi.update_layout(height=250, margin=dict(t=10))

        st.plotly_chart(fig_price, use_container_width=True)
        st.plotly_chart(fig_macd, use_container_width=True)
        st.plotly_chart(fig_rsi, use_container_width=True)

        # Data table (latest rows)
        st.subheader('Latest data snapshot')
        st.dataframe(df.tail(10))

        # Backtest
        st.subheader('Simple backtest (example rule: buy when score>30, sell when score<-30)')
        bt = simple_backtest(df)
        st.write('Total return (simulated, 1 unit trades):', bt['total_return'])
        st.write('Trades:')
        for t in bt['trades']:
            st.write(t)

        # Export / CSV
        csv = df.to_csv().encode('utf-8')
        st.download_button(label='Download data as CSV', data=csv, file_name=f'{ticker}_data.csv', mime='text/csv')

        st.info('Reminder: This is a demo rule-based analyzer. Combine with fundamental research before taking real positions.')

# Footer / quick help
st.markdown('---')
st.caption('Built with Streamlit — live data via yfinance. For production use, incorporate proper error handling, rate-limiting, and a broker API for execution.')
